// Slim dataset for the footprint calculator
// Only includes fields needed for CO2, water, and raw cost calculations
// Full data at: https://github.com/jonsims/iphone-minerals

const materials = {
  "stainless-steel": { pricePerKg: 3.5, eco: { co2PerKg: 6.15, waterPerKg: 56 } },
  aluminum:          { pricePerKg: 2.5, eco: { co2PerKg: 11.5, waterPerKg: 1058 } },
  titanium:          { pricePerKg: 35,  eco: { co2PerKg: 36, waterPerKg: 105 } },
  glass:             { pricePerKg: 1.5, eco: { co2PerKg: 1.2, waterPerKg: 7 } },
  lithium:           { pricePerKg: 25,  eco: { co2PerKg: 15, waterPerKg: 1900 } },
  cobalt:            { pricePerKg: 33,  eco: { co2PerKg: 8.3, waterPerKg: 300 } },
  nickel:            { pricePerKg: 18,  eco: { co2PerKg: 13, waterPerKg: 370 } },
  graphite:          { pricePerKg: 1.5, eco: { co2PerKg: 1.8, waterPerKg: 30 } },
  copper:            { pricePerKg: 8.5, eco: { co2PerKg: 3.5, waterPerKg: 260 } },
  "rare-earths":     { pricePerKg: 220, eco: { co2PerKg: 32, waterPerKg: 1200 } },
  tungsten:          { pricePerKg: 35,  eco: { co2PerKg: 12.5, waterPerKg: 380 } },
  tantalum:          { pricePerKg: 180, eco: { co2PerKg: 70, waterPerKg: 4000 } },
  tin:               { pricePerKg: 26,  eco: { co2PerKg: 16, waterPerKg: 350 } },
  gold:              { pricePerKg: 62000, eco: { co2PerKg: 17000, waterPerKg: 260000 } },
  silver:            { pricePerKg: 780, eco: { co2PerKg: 196, waterPerKg: 7700 } },
  silicon:           { pricePerKg: 2.8, eco: { co2PerKg: 11.5, waterPerKg: 1500 } },
  plastics:          { pricePerKg: 2.0, eco: { co2PerKg: 3.5, waterPerKg: 14 } },
};

const phones = [
  {
    id: "iphone-x", name: "iPhone X", year: 2017, carbonFootprint: 79,
    materials: [
      { id: "stainless-steel", grams: 55 }, { id: "glass", grams: 32 },
      { id: "lithium", grams: 0.9 }, { id: "cobalt", grams: 6.5 },
      { id: "nickel", grams: 3.0 }, { id: "graphite", grams: 10 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.0 },
      { id: "tungsten", grams: 5.0 }, { id: "tantalum", grams: 0.02 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 }, { id: "silicon", grams: 2.5 },
      { id: "plastics", grams: 14 },
    ],
  },
  {
    id: "iphone-xr", name: "iPhone XR", year: 2018, carbonFootprint: 62,
    materials: [
      { id: "aluminum", grams: 28 }, { id: "glass", grams: 30 },
      { id: "lithium", grams: 1.0 }, { id: "cobalt", grams: 6.0 },
      { id: "nickel", grams: 3.2 }, { id: "graphite", grams: 11 },
      { id: "copper", grams: 14 }, { id: "rare-earths", grams: 1.0 },
      { id: "tungsten", grams: 4.5 }, { id: "tantalum", grams: 0.018 },
      { id: "tin", grams: 1.8 }, { id: "gold", grams: 0.03 },
      { id: "silver", grams: 0.3 }, { id: "silicon", grams: 2.5 },
      { id: "plastics", grams: 16 },
    ],
  },
  {
    id: "iphone-xs", name: "iPhone XS", year: 2018, carbonFootprint: 70,
    materials: [
      { id: "stainless-steel", grams: 54 }, { id: "glass", grams: 34 },
      { id: "lithium", grams: 0.9 }, { id: "cobalt", grams: 6.2 },
      { id: "nickel", grams: 3.1 }, { id: "graphite", grams: 10 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.0 },
      { id: "tungsten", grams: 5.0 }, { id: "tantalum", grams: 0.02 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 }, { id: "silicon", grams: 2.5 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-11", name: "iPhone 11", year: 2019, carbonFootprint: 72,
    materials: [
      { id: "aluminum", grams: 30 }, { id: "glass", grams: 32 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 6.3 },
      { id: "nickel", grams: 3.5 }, { id: "graphite", grams: 12 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.1 },
      { id: "tungsten", grams: 4.5 }, { id: "tantalum", grams: 0.018 },
      { id: "tin", grams: 1.8 }, { id: "gold", grams: 0.03 },
      { id: "silver", grams: 0.3 }, { id: "silicon", grams: 2.5 },
      { id: "plastics", grams: 16 },
    ],
  },
  {
    id: "iphone-11-pro", name: "iPhone 11 Pro", year: 2019, carbonFootprint: 80,
    materials: [
      { id: "stainless-steel", grams: 56 }, { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 6.0 },
      { id: "nickel", grams: 3.5 }, { id: "graphite", grams: 11 },
      { id: "copper", grams: 16 }, { id: "rare-earths", grams: 1.1 },
      { id: "tungsten", grams: 5.5 }, { id: "tantalum", grams: 0.02 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 }, { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-12", name: "iPhone 12", year: 2020, carbonFootprint: 70,
    materials: [
      { id: "aluminum", grams: 26 }, { id: "glass", grams: 33 },
      { id: "lithium", grams: 1.0 }, { id: "cobalt", grams: 5.5 },
      { id: "nickel", grams: 3.8 }, { id: "graphite", grams: 11 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 4.5 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 1.8 }, { id: "gold", grams: 0.03 },
      { id: "silver", grams: 0.3 }, { id: "silicon", grams: 2.8 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-12-pro", name: "iPhone 12 Pro", year: 2020, carbonFootprint: 82,
    materials: [
      { id: "stainless-steel", grams: 60 }, { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 5.5 },
      { id: "nickel", grams: 4.0 }, { id: "graphite", grams: 12 },
      { id: "copper", grams: 16 }, { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 5.5 }, { id: "tantalum", grams: 0.018 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 }, { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-13", name: "iPhone 13", year: 2021, carbonFootprint: 64,
    materials: [
      { id: "aluminum", grams: 26 }, { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 5.2 },
      { id: "nickel", grams: 4.0 }, { id: "graphite", grams: 12 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 4.5 }, { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.8 }, { id: "gold", grams: 0.03 },
      { id: "silver", grams: 0.3 }, { id: "silicon", grams: 2.8 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-13-pro", name: "iPhone 13 Pro", year: 2021, carbonFootprint: 69,
    materials: [
      { id: "stainless-steel", grams: 62 }, { id: "glass", grams: 37 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 5.0 },
      { id: "nickel", grams: 4.2 }, { id: "graphite", grams: 12 },
      { id: "copper", grams: 17 }, { id: "rare-earths", grams: 1.3 },
      { id: "tungsten", grams: 5.5 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 }, { id: "silicon", grams: 3.2 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-14", name: "iPhone 14", year: 2022, carbonFootprint: 61,
    materials: [
      { id: "aluminum", grams: 25 }, { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.1 }, { id: "cobalt", grams: 5.0 },
      { id: "nickel", grams: 4.2 }, { id: "graphite", grams: 13 },
      { id: "copper", grams: 15 }, { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 4.0 }, { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.8 }, { id: "gold", grams: 0.032 },
      { id: "silver", grams: 0.32 }, { id: "silicon", grams: 2.8 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-14-pro", name: "iPhone 14 Pro", year: 2022, carbonFootprint: 65,
    materials: [
      { id: "stainless-steel", grams: 62 }, { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.2 }, { id: "cobalt", grams: 4.9 },
      { id: "nickel", grams: 4.3 }, { id: "graphite", grams: 12.5 },
      { id: "copper", grams: 17 }, { id: "rare-earths", grams: 1.3 },
      { id: "tungsten", grams: 5.5 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 }, { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-15", name: "iPhone 15", year: 2023, carbonFootprint: 56,
    materials: [
      { id: "aluminum", grams: 25 }, { id: "stainless-steel", grams: 12 },
      { id: "glass", grams: 34 }, { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 4.2 }, { id: "nickel", grams: 5.0 },
      { id: "graphite", grams: 13.5 }, { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.3 }, { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 }, { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 }, { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 }, { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-15-pro", name: "iPhone 15 Pro", year: 2023, carbonFootprint: 56,
    materials: [
      { id: "titanium", grams: 22 }, { id: "aluminum", grams: 12 },
      { id: "stainless-steel", grams: 10 }, { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.2 }, { id: "cobalt", grams: 4.0 },
      { id: "nickel", grams: 5.2 }, { id: "graphite", grams: 13 },
      { id: "copper", grams: 17 }, { id: "rare-earths", grams: 1.4 },
      { id: "tungsten", grams: 5.0 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 }, { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 10 },
    ],
  },
  {
    id: "iphone-16", name: "iPhone 16", year: 2024, carbonFootprint: 56,
    materials: [
      { id: "aluminum", grams: 25 }, { id: "stainless-steel", grams: 11 },
      { id: "glass", grams: 34 }, { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 3.8 }, { id: "nickel", grams: 5.5 },
      { id: "graphite", grams: 14 }, { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.4 }, { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 }, { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 }, { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 }, { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-16-pro", name: "iPhone 16 Pro", year: 2024, carbonFootprint: 56,
    materials: [
      { id: "titanium", grams: 24 }, { id: "aluminum", grams: 13 },
      { id: "stainless-steel", grams: 10 }, { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.3 }, { id: "cobalt", grams: 3.6 },
      { id: "nickel", grams: 5.8 }, { id: "graphite", grams: 14 },
      { id: "copper", grams: 18 }, { id: "rare-earths", grams: 1.5 },
      { id: "tungsten", grams: 5.0 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 }, { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 10 },
    ],
  },
  {
    id: "iphone-17", name: "iPhone 17", year: 2025, carbonFootprint: 52,
    materials: [
      { id: "aluminum", grams: 24 }, { id: "stainless-steel", grams: 10 },
      { id: "glass", grams: 34 }, { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 3.4 }, { id: "nickel", grams: 5.8 },
      { id: "graphite", grams: 14.5 }, { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.5 }, { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 }, { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 }, { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 }, { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-17-pro", name: "iPhone 17 Pro", year: 2025, carbonFootprint: 54,
    materials: [
      { id: "titanium", grams: 20 }, { id: "aluminum", grams: 16 },
      { id: "stainless-steel", grams: 8 }, { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.4 }, { id: "cobalt", grams: 3.2 },
      { id: "nickel", grams: 6.0 }, { id: "graphite", grams: 15 },
      { id: "copper", grams: 18 }, { id: "rare-earths", grams: 1.5 },
      { id: "tungsten", grams: 5.0 }, { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 }, { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 }, { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 9 },
    ],
  },
];
